"""'addaaa'

Revision ID: 38fbe6787849
Revises: f4fb4f068edd
Create Date: 2023-07-24 11:20:31.990029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fbe6787849'
down_revision = 'f4fb4f068edd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('president', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
