"""First migration

Revision ID: 4df2ecd5bded
Revises: 8bcc83a25447
Create Date: 2023-07-19 09:02:02.337384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df2ecd5bded'
down_revision = '8bcc83a25447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('definition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'definition')
    # ### end Alembic commands ###
