"""first migration

Revision ID: c077abed42ed
Revises: 
Create Date: 2023-07-18 23:21:56.408162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c077abed42ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('associations', sa.JSON(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
