"""'addmap'

Revision ID: f4fb4f068edd
Revises: 4df2ecd5bded
Create Date: 2023-07-24 11:18:05.448755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fb4f068edd'
down_revision = '4df2ecd5bded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
